"""11/01/2026 - Editing Chat and Adding hashed_password to user

Revision ID: 47823060d727
Revises: 6c4e69f50ed8
Create Date: 2026-01-11 01:19:38.732934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '47823060d727'
down_revision: Union[str, Sequence[str], None] = '6c4e69f50ed8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
